### ISSUE TITLE
dojo/topic publish function should use rest parameters instead of a single parameter

### ISSUE THREAD

**Issue by nickp10** [dojo/typings#30]
The publish function in the Topic interface should use the rest parameters feature defined here: https://www.typescriptlang.org/docs/handbook/functions.html. Instead of:

`publish(topic: string | ExtensionEvent, event: any): boolean;`

It can be written as:

`publish(topic: string | ExtensionEvent, ...event: any[]): boolean;`

**Comment by kitsonk** [comment]
This is not the API.  Though it works in certain cases based on they way the code is working, it was never intended that `publish()` would support multiple events.  It would be unsafe to add that signature because people would then rely upon unintended behaviour of the code.  This is one of the good things in TypeScript is we can enforce the intent of the code.

From a code perspective, `publish()` uses `Evented.emit()` which uses `on.emit()` which in turn uses an internal function called `syntheticDispatch()` when it is not a DOM target, which does pass whatever arguments, but only under certain conditions.

Thanks for the feedback though.

**Comment by nickp10** [comment]
According to the [API documentation](https://dojotoolkit.org/api/?qs=1.10/dojo/topic):

> All arguments after the first will be passed to the subscribers, so any number of arguments can be provided (not just event).

I would assume the TypeScript definitions would need to represent what the API documentation is stating.

**Comment by kitsonk** [comment]
Yes I see that is in the source comments and there is a [test for it](https://github.com/dojo/dojo/blob/a97b1aef3fbc442cf0302ddb519382fcd6515c79/tests/unit/topic.js#L60) as well, so even though the chain is rather "fragile" in my opinion of how it was delivered, it was clearly intentional.
