### ISSUE TITLE
Work with @types to publish parts of this repo versus DefinitelyTyped

### ISSUE THREAD

**Issue by kitsonk** [dojo/typings#39]
We should work with the team @types to be able to leverage the parts of this repo to package up and replace what is currently being published to the `@types` namespace for the projects that are part of the Dojo Toolkit (e.g. `@types/dojo`).

**Comment by dylans** [comment]
This should be easier to achieve once https://github.com/Microsoft/types-publisher/issues/4 is solved.

**Comment by HeikoStudt** [comment]
Ping: That issue is like 4 years old and seems not to be solved in the near future, though.
There is a real issue for us currently, as @types/dojo does have some wrong types, while e.g. dojo-dstore is referencing @types/dojo.

We are not sure whether to contribute fixes to either @types/dojo or here, both look like to be somewhat half-maintained.

**Comment by dylans** [comment]
Hi @HeikoStudt, thanks for the feedback and PRs here and in dstore. This package is maintained more in my opinion, mostly as people like you suggest changes and improvements. We'll review your PRs asap. Please make sure you've approved the Contributor License Agreement (CLA) in at least one of the PRs so we can accept your contributions.

**Comment by HeikoStudt** [comment]
Hi @dylans,
thanks a lot. Are there any plans to merge the two typings? Especially interesting are the generic/non-generic Deferred, where both variants are surely depended upon by a lot of existing code.
PS: I needed to put up new PRs for being able to sign - my apologies about that.

MFG (Kind Regards)
